prototype(Neos.Fusion:Testing.Throwing).@class = 'TYPO3\\TypoScript\\Tests\\Functional\\TypoScriptObjects\\Fixtures\\TypoScriptObjects\\ThrowingImplementation'

exceptionHandler.eelExpressionInProperty = Neos.Fusion:Array {
	start = 'Start'
	error = Neos.Fusion:Collection {
		collection = ${Testing.Utility.throwException()}

		@exceptionHandler = 'TYPO3\\TypoScript\\Core\\ExceptionHandlers\\PlainTextHandler'
	}
	end = 'End'
}

exceptionHandler.eelExpressionInOverride = Neos.Fusion:Array {
	start = 'Start'
	error = Neos.Fusion:Collection {
		@context.myCollection = ${Testing.Utility.throwException()}
		collection = ${myCollection}
		itemName = 'item'

		@exceptionHandler = 'TYPO3\\TypoScript\\Core\\ExceptionHandlers\\PlainTextHandler'
	}
	end = 'End'
}


exceptionHandler.nestedHandlerIsEvaluated = Neos.Fusion:Value {
	value = Neos.Fusion:Testing.Throwing {
		shouldThrow = TRUE
		@exceptionHandler = 'TYPO3\\TypoScript\\Core\\ExceptionHandlers\\PlainTextHandler'
	}
}
